### ISSUE TITLE
Master task list

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/3DTG#4]
## Priority 1 features:
- [ ] #21
- [ ] #23
- [ ] #25
- [ ] #27

At this point we should have a fully functional first prototype pipeline for generating 3D Tiles from an OBJ file input. 
After this point we can proceed with Priority 2 and 3 tasks.

## Priority 2 features:
- [ ] #11
- [ ] #16
- [ ] #20
- [ ] #22
- [ ] #24

## Priority 3 features:

- [ ] #17

## Nice to have (lowest priority/complete later):
- [ ] #9
- [ ] #12
- [ ] Point cloud 3d tiles
- [ ] Determine average edge length and min edge length of a polygon edge. Use this to determine what precision is required for the DRACO compression

## Fixes:
- [ ] ...

## Completed:
- [x] Fix LOD generation so that it produces the correct sub-volumes as textured OBJ files.
- [x] #5
- [x] #15
- [x] #14
- [x] #18
- [x] #19
- [x] #6
- [x] #7
- [x] #8
- [x] #10
